Read .uv-version in install checker

diff --git a/uv b/uv
--- a/uv
+++ b/uv
@@ -18,26 +18,6 @@ set -eE
 
 THISDIR=$(dirname "$0")
 
-UV_VERSION=$(head -n 1 "$THISDIR/.uv-version" 2>/dev/null || true)
-
-# Remove leading and trailing whitespaces from the version string
-UV_VERSION=${UV_VERSION#"${UV_VERSION%%[![:space:]]*}"}
-UV_VERSION=${UV_VERSION%"${UV_VERSION##*[![:space:]]}"}
-
-# Validate UV_VERSION if set. We are only allowing stable versions here. If
-# this is too strict, we can easily remove the following block in the future.
-if [ "$UV_VERSION" ]; then
-  if ! [[ "$UV_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-    {
-      echo "! Invalid version format in .uv-version: $UV_VERSION"
-      echo "! Expected format: X.Y.Z (e.g., 0.1.0)"
-      echo "! Leave it empty or remove the file to automatically"
-      echo "!   pick the latest release!"
-    } >&2
-    exit 1
-  fi
-fi
-
 UV_ARCH=$(uname -m)
 case "$UV_ARCH" in
   x86_64 | amd64) UV_ARCH="x86_64" ;;
@@ -206,6 +186,28 @@ download() {
 }
 
 is_uv_installed() {
+  if [ ! "$UV_VERSION" ]; then
+    UV_VERSION=$(head -n 1 "$THISDIR/.uv-version" 2>/dev/null || true)
+
+    # Remove leading and trailing whitespaces from the version string
+    UV_VERSION=${UV_VERSION#"${UV_VERSION%%[![:space:]]*}"}
+    UV_VERSION=${UV_VERSION%"${UV_VERSION##*[![:space:]]}"}
+
+    # Validate UV_VERSION if set. We are only allowing stable versions here. If
+    # this is too strict, we can easily remove the following block in the future.
+    if [ "$UV_VERSION" ]; then
+      if ! [[ "$UV_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+        {
+          echo "! Invalid version format in .uv-version: $UV_VERSION"
+          echo "! Expected format: X.Y.Z (e.g., 0.1.0)"
+          echo "! Leave it empty or remove the file to automatically"
+          echo "!   pick the latest release!"
+        } >&2
+        exit 1
+      fi
+    fi
+  fi
+
   [ "$UV_VERSION" ] &&
     [ -x "$UV_BIN_DIR/$UV_EXE" ] &&
     [[ "$("$UV_BIN_DIR/$UV_EXE" --version)" = "uv $UV_VERSION "* ]]
